### ISSUE TITLE
Add more information

### ISSUE THREAD

**Issue by Atharv181** [pcaversaccio/reentrancy-attacks#7]
Hey can you add how it happens and what should we take care of while writing the code

**Comment by pcaversaccio** [comment]
@Atharv181 thanks a lot for the issue - for each attack you find the link to the post-mortem so you can read about what went wrong and how to prevent it (for most cases). Generally, there have been written numerous articles on how to prevent reentrancy attacks (e.g. use a [`ReentrancyGuard`](https://docs.openzeppelin.com/contracts/4.x/api/security#ReentrancyGuard) or the [Checks-Effects-Interactions](https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html) pattern). You could get started with the [ConsenSys article](https://consensys.github.io/smart-contract-best-practices/attacks/reentrancy/). Note, for cross-contract or [read-only reentrancy](https://chainsecurity.com/curve-lp-oracle-manipulation-post-mortem/) attacks, special care has been taken since coordination across multiple contracts is needed.

This repository is not intended for a technical deep-dive of reentrancy attacks but rather collecting the attack informations, I will close this issue.

**Comment by Atharv181** [comment]
Thank you @pcaversaccio for your response and for sharing the resources it will help me to learn more :)
